<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 --transform --root ./static --types --keepnames --precision 6 ./static/astronaut-helmet.glb
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Visor: THREE.Mesh
      ['Helmet-Inner']: THREE.Mesh
      Cylinder: THREE.Mesh
      Sphere004: THREE.Mesh
      Sphere004_1: THREE.Mesh
      ['Helmet-Inner001']: THREE.Mesh
      Cylinder001: THREE.Mesh
      Cylinder002: THREE.Mesh
      RetopoFlow088: THREE.Mesh
      RetopoFlow088_1: THREE.Mesh
    }
    materials: {
      Visor: THREE.MeshPhysicalMaterial
      Material: THREE.MeshStandardMaterial
      Metal: THREE.MeshStandardMaterial
      Brass: THREE.MeshStandardMaterial
      skull: THREE.MeshStandardMaterial
      ['skull.001']: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('/astronaut-helmet-transformed.glb', { useDraco: true })
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="Visor"
      geometry={$gltf.nodes.Visor.geometry}
      material={$gltf.materials.Visor}
      position={[0, 0.376172, 0]}
    />
    <T.Mesh
      name="Helmet-Inner"
      geometry={$gltf.nodes['Helmet-Inner'].geometry}
      material={$gltf.materials.Material}
      position={[0, 0.376172, 0]}
      rotation={[0.49625, 0, 0]}
    />
    <T.Mesh
      name="Cylinder"
      geometry={$gltf.nodes.Cylinder.geometry}
      material={$gltf.materials.Metal}
      position={[0, 0.005558, 0.04802]}
      rotation={[-0.070662, 0, 0]}
    />
    <T.Group name="Sphere" position={[0, 0.376172, 0]} rotation={[0.128762, 0, 0]}>
      <T.Mesh
        name="Sphere004"
        geometry={$gltf.nodes.Sphere004.geometry}
        material={$gltf.materials.Material}
      />
      <T.Mesh
        name="Sphere004_1"
        geometry={$gltf.nodes.Sphere004_1.geometry}
        material={$gltf.materials.Metal}
      />
    </T.Group>
    <T.Mesh
      name="Helmet-Inner001"
      geometry={$gltf.nodes['Helmet-Inner001'].geometry}
      material={$gltf.materials.Metal}
      position={[0, 0.376172, 0]}
      rotation={[0.49625, 0, 0]}
    />
    <T.Mesh
      name="Cylinder001"
      geometry={$gltf.nodes.Cylinder001.geometry}
      material={$gltf.materials.Brass}
      position={[0.519512, 0.397029, -0.080712]}
      rotation={[-0.007107, 0.106379, -1.503963]}
    />
    <T.Mesh
      name="Cylinder002"
      geometry={$gltf.nodes.Cylinder002.geometry}
      material={$gltf.materials.Brass}
      position={[0.469201, 0.156996, -0.041707]}
      rotation={[0, 0.103374, -1.901089]}
      scale={[0.06344, 0.022211, 0.06344]}
    />
    <T.Group name="skull" position={[0.000223, 0.300358, 0.064092]}>
      <T.Mesh
        name="RetopoFlow088"
        geometry={$gltf.nodes.RetopoFlow088.geometry}
        material={$gltf.materials.skull}
      />
      <T.Mesh
        name="RetopoFlow088_1"
        geometry={$gltf.nodes.RetopoFlow088_1.geometry}
        material={$gltf.materials['skull.001']}
      />
    </T.Group>

    <slot {ref} />
  </Three>
{/if}
