<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 --transform --root ./static --types --keepnames --precision 6 ./assets/astronaut-helmet.glb
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Visor001: THREE.Mesh
      Helmet_001: THREE.Mesh
      Attachment001: THREE.Mesh
      Port001: THREE.Mesh
      ['Accessory_-_side001']: THREE.Mesh
      Accessory001: THREE.Mesh
      Partition001: THREE.Mesh
      ['Helmet_-_metal001']: THREE.Mesh
      Coupling001: THREE.Mesh
    }
    materials: {
      Visor: THREE.MeshPhysicalMaterial
      Material: THREE.MeshStandardMaterial
      ['Metal.001']: THREE.MeshStandardMaterial
      Black: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('./astronaut-helmet-transformed.glb', { useDraco: true })
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh
      name="Visor001"
      geometry={$gltf.nodes.Visor001.geometry}
      material={$gltf.materials.Visor}
      position={[0, 0.376172, 0]}
    />
    <T.Mesh
      name="Helmet_001"
      geometry={$gltf.nodes.Helmet_001.geometry}
      material={$gltf.materials.Material}
      position={[0, 0.376172, 0]}
      rotation={[0.128762, 0, 0]}
    />
    <T.Mesh
      name="Attachment001"
      geometry={$gltf.nodes.Attachment001.geometry}
      material={$gltf.materials['Metal.001']}
      position={[0.519512, 0.397029, -0.080712]}
      rotation={[-0.007107, 0.106379, -1.503963]}
    />
    <T.Mesh
      name="Port001"
      geometry={$gltf.nodes.Port001.geometry}
      material={$gltf.materials['Metal.001']}
      position={[0.469201, 0.156996, -0.041707]}
      rotation={[0, 0.103374, -1.901089]}
    />
    <T.Mesh
      name="Accessory_-_side001"
      geometry={$gltf.nodes['Accessory_-_side001'].geometry}
      material={$gltf.materials.Material}
      position={[0.836674, 0.318586, 0.044687]}
      rotation={[-0.327226, 0, 0]}
    />
    <T.Mesh
      name="Accessory001"
      geometry={$gltf.nodes.Accessory001.geometry}
      material={$gltf.materials.Material}
      position={[0.272551, 0.088361, 0.102818]}
      rotation={[0, -0.088397, 0]}
    />
    <T.Mesh
      name="Partition001"
      geometry={$gltf.nodes.Partition001.geometry}
      material={$gltf.materials.Black}
      position={[0, 0.005558, 0.04802]}
    />
    <T.Mesh
      name="Helmet_-_metal001"
      geometry={$gltf.nodes['Helmet_-_metal001'].geometry}
      material={$gltf.materials['Metal.001']}
      position={[0, 0.376172, 0]}
      rotation={[0.49625, 0, 0]}
    />
    <T.Mesh
      name="Coupling001"
      geometry={$gltf.nodes.Coupling001.geometry}
      material={$gltf.materials['Metal.001']}
      position={[0, 0.005558, 0.04802]}
      rotation={[-0.070662, 0, 0]}
    />

    <slot {ref} />
  </Three>
{/if}
