<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 --transform --root ./static --types --keepnames --precision 6 ./assets/mushrooms.glb
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, Three, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Mushroom_: THREE.Mesh
    }
    materials: {
      Mushroom: THREE.MeshStandardMaterial
    }
  }

  const { gltf } = useGltf<GLTFResult>('./mushrooms-transformed.glb', { useDraco: true })
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh name="Mushroom_" geometry={$gltf.nodes.Mushroom_.geometry} material={$gltf.materials.Mushroom} />

    <slot {ref} />
  </Three>
{/if}
